### ISSUE TITLE
Hey man, I know this is pretty unrelated but you’ve really got to help us here!

### ISSUE THREAD

**Issue by TheMamaMiaGuy** [Hydr8gon/sodium64#1]
Remember that Super Mario 64 DSi port you were developing? When are you ever going to resolve some of its audio and visual issues like no sound, rendering problems and framerate drops? You had something really good brewing in kitchen until you turned the burner off. Me and the fans would appreciate that you continue squashing all of those bugs crawling around within…

**Comment by Hydr8gon** [comment]
I might return to it at some point, but my interests and motivation tend to jump around a lot. Though honestly, I think it's in a pretty decent state already; there are no major rendering issues, audio works well most of the time, and it probably lags less than the unoptimized N64 build does on actual hardware. Of course there are still improvements to be made, but I guess I wanted to work on other things for a while.

(Also, you can make issues on the SM64DSi repo, I'll still get notifications for it :P)

**Comment by TheMamaMiaGuy** [comment]
Ok, I see. My interests hop around from time to time as well. I think I may have an outdated build because I often get glitches like when it soft locks after getting back to the castle after collecting a star. I also get framerate drops in bob-omb battlefield.
