### ISSUE TITLE
Mode 7 rendering in Wolfenstein 3D *almost* works

### ISSUE THREAD

**Issue by thekovic** [Hydr8gon/sodium64#14]
I hope it's appropriate to report game-specific issues. See image attached for the problem (I think it's more obvious than me trying to describe it). Despite that, the game is actually still kinda playable, though obviously not ideal. Even the emulation speed isn't bad.

![IMG_20240602_011551](https://github.com/Hydr8gon/sodium64/assets/72971433/2ae32f87-7aca-4ca9-af17-06f7875974ae)

**Comment by Hydr8gon** [comment]
I think this is because of unimplemented VRAM address translation.

**Comment by Hydr8gon** [comment]
I think this is due to unimplemented VRAM address translation; it should be easy to add.
